PMS/Models/ErrorViewModel.cs
namespace PMS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PMS/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace PMS.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();

        }
        public IActionResult Register()
        {
            return View();

        }
    }
}

PMS/Controllers/BreaderController.cs
using Microsoft.AspNetCore.Mvc;

namespace PMS.Controllers
{
    public class BreaderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PMS/Controllers/BroilerController.cs
using Microsoft.AspNetCore.Mvc;

namespace PMS.Controllers
{
    public class BroilerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PMS/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace PMS.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PMS/Controllers/DealerController.cs
using Microsoft.AspNetCore.Mvc;

namespace PMS.Controllers
{
    public class DealerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PMS/Controllers/RetailerController.cs
using Microsoft.AspNetCore.Mvc;

namespace PMS.Controllers
{
    public class RetailerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PMS/Views/Breader/Index.cshtml
@* Views/Breader/index.cshtml *@

 
<div id="layoutSidenav_content">
             <p>Breader<p>

            </div>
     

PMS/Views/Broiler/Index.cshtml
@* Views/Broiler/index.cshtml *@

 
<div id="layoutSidenav_content">
             <p>Broiler<p>

            </div>
     

PMS/Views/Dealer/Index.cshtml
@* Views/Dealer/index.cshtml *@

 
<div id="layoutSidenav_content">
             <p>Dealer<p>

            </div>
     

PMS/Views/Retailer/Index.cshtml
 
@* Views/Dashboard/Inxex.cshtml *@
@* Views/Retailer/index.cshtml *@

 
<div id="layoutSidenav_content">
             <p>Retailer<p>

            </div>
     

PMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Poltary Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PMS.styles.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/lib/admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

</head>
<body class="sb-nav-fixed">
 
 


        

       @if (Context.Request.Path != "/Account/Login" && Context.Request.Path != "/Account/Register")
    {
      
     @await Html.PartialAsync("_TopNavBar")
      <div id="layoutSidenav">
       @await Html.PartialAsync("_SideNavBar")
        @RenderBody()
      </div>
    }
    else
    {
        <div class="bg-primary">
        <main>
            @RenderBody()
        </main>
        </div>
    }




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="~/lib/admin/js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="~/lib/admin/assets/demo/chart-area-demo.js"></script>
        <script src="~/lib/admin/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="~/lib/admin/js/datatables-simple-demo.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PMS/Views/Shared/_SideNavBar.cshtml
  <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>

                    <!-- Retailer Section -->
                    <a class="nav-link collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseRetailer" aria-expanded="false" aria-controls="collapseRetailer" >
                        <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                        Retailer
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseRetailer" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" asp-controller="Retailer" asp-action="Index">Retailer List</a>
                            <a class="nav-link" href="add-new-retailer.html">Add New Retailer</a>
                        </nav>
                    </div>

                    <!-- Dealer Section -->
                    <a class="nav-link collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseDealer" aria-expanded="false" aria-controls="collapseDealer" >
                        <div class="sb-nav-link-icon"><i class="fas fa-store"></i></div>
                        Dealer
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseDealer" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" asp-controller="Dealer" asp-action="Index">Dealer List</a>
                            <a class="nav-link" href="add-new-dealer.html">Add New Dealer</a>
                        </nav>
                    </div>

                    <!-- Broiler Section -->
                    <a class="nav-link collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseBroiler" aria-expanded="false" aria-controls="collapseBroiler" >
                        <div class="sb-nav-link-icon"><i class="fas fa-drumstick-bite"></i></div>
                        Broiler
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseBroiler" aria-labelledby="headingThree" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" asp-controller="Broiler" asp-action="Index">Broiler List</a>
                            <a class="nav-link" href="add-new-broiler.html">Add New Broiler</a>
                        </nav>
                    </div>

                    <!-- Breeder Section -->
                    <a class="nav-link collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseBreeder" aria-expanded="false" aria-controls="collapseBreeder" >
                        <div class="sb-nav-link-icon"><i class="fas fa-egg"></i></div>
                        Breeder
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseBreeder" aria-labelledby="headingFour" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" asp-controller="Breader" asp-action="Index">Breeder List</a>
                            <a class="nav-link" href="add-new-breeder.html">Add New Breeder</a>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                Your Username
            </div>
        </nav>
    </div>

PMS/Views/Shared/_TopNavBar.cshtml
  
@* Views/Shared/_TopNavBar.cshtml *@

  <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">PMS</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Settings</a></li>
                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="#!">Logout</a></li>
                    </ul>
                </li>
            </ul>
   </nav>